Repository csinn/Painted-Prosthetics, pull requests merged in 2020-06, with the labels that each got.

#15 Wireframe for Mobile app Design
  Documents/AppWireframe/ArtClicked.png
  Documents/AppWireframe/DrawingWindow.png
  Documents/AppWireframe/FanArtSubmission.png
  Documents/AppWireframe/Gallery Choice.png
  Documents/AppWireframe/Links to WireFrame.CC.txt
  Documents/AppWireframe/Login.png
  Documents/AppWireframe/ProfessionalAndFanGallery.png
  Documents/AppWireframe/Settings.png
  Documents/AppWireframe/Wireframe.cc.url
Labels: frontend, specification

#25 Mobile app use cases
  Documents/MobileAppActors.md
  Documents/MobileAppUseCases.PNG
  Documents/MobileAppUseCases.drawio
Labels: planned 1, specification

#24 Website use cases
  Docs/UML/Mobile/UseCases/Mobile app use cases.PNG
  Docs/UML/Mobile/UseCases/Mobile app use cases.drawio
  Docs/UML/Mobile/UseCases/Mobile app use cases.md
  Docs/UML/Mobile/Wireframe/ArtClicked.png
  Docs/UML/Mobile/Wireframe/DrawingWindow.png
  Docs/UML/Mobile/Wireframe/FanArtSubmission.png
  Docs/UML/Mobile/Wireframe/Gallery Choice.png
  Docs/UML/Mobile/Wireframe/Links to WireFrame.CC.txt
  Docs/UML/Mobile/Wireframe/Login.png
  Docs/UML/Mobile/Wireframe/ProfessionalAndFanGallery.png
  Docs/UML/Mobile/Wireframe/Settings.png
  Docs/UML/Mobile/Wireframe/Wireframe.cc.url
  Docs/UML/Website/UseCases/Website use cases.drawio
  Docs/UML/Website/UseCases/Website use cases.md
  Docs/UML/Website/UseCases/Website use cases.png
  Documents/DrawIO_HowTo.txt
  Documents/MobileAppActors.txt
  Documents/UseCasesForWebsite.txt
Labels: planned 3, specification

#26 Website wireframe
  Documents/DrawIO_HowTo.txt
  Documents/MobileAppActors.md
  Documents/MobileAppActors.txt
  Documents/MobileAppUseCases.PNG
  Documents/MobileAppUseCases.drawio
  Documents/UseCasesForWebsite.txt
  Documents/WebsiteWireframe/Pics/AdminAmputeeManagement.png
  Documents/WebsiteWireframe/Pics/AdminArtistAvailability.png
  Documents/WebsiteWireframe/Pics/AdminArtistManagement.png
  Documents/WebsiteWireframe/Pics/AdminDonations.png
  Documents/WebsiteWireframe/Pics/AdminFanGalleryManagement.png
  Documents/WebsiteWireframe/Pics/AdminFeedback.png
  Documents/WebsiteWireframe/Pics/AdminProGalleryManagement.png
  Documents/WebsiteWireframe/Pics/ArtistAvailability.png
  Documents/WebsiteWireframe/Pics/ArtistManagePortofolio.png
  Documents/WebsiteWireframe/Pics/ArtistPage.png
  Documents/WebsiteWireframe/Pics/Donate.png
  Documents/WebsiteWireframe/Pics/Info.png
  Documents/WebsiteWireframe/Pics/Login.png
  Documents/WebsiteWireframe/Pics/MenuBarFooter.png
  Documents/WebsiteWireframe/Pics/Register.png
  Documents/WebsiteWireframe/Pics/UserRequestProsthetic.png
  Documents/WebsiteWireframe/Pics/UserSentArtistApplication.png
  Documents/WebsiteWireframe/Pics/UserSentProstheticRequest.png
  Documents/WebsiteWireframe/Pics/gallery.png
  Documents/WebsiteWireframe/Pics/userArtistApply.png
  Documents/WebsiteWireframe/Pics/userPersonalInfo.png
  Documents/WebsiteWireframe/wireframeCC.txt
Labels: actual 3, frontend, planned 5, specification
